AY2425S2-CS2103T-W12-4/tp

- docs/AboutUs.md
- docs/team/harbour.md
> Update AboutUs - Harbour

- docs/_config.yml
- docs/_sass/minima/_base.scss
> Update project website header and repo

- docs/DeveloperGuide.md
> Add user stories to developer guide

- docs/DeveloperGuide.md
> Add NFRs to developer guide

- README.md
> Acknowledge original source code

- src/main/java/tassist/address/logic/Messages.java
- src/main/java/tassist/address/logic/commands/AddCommand.java
- src/main/java/tassist/address/logic/commands/EditCommand.java
- src/main/java/tassist/address/logic/parser/AddCommandParser.java
- src/main/java/tassist/address/logic/parser/CliSyntax.java
- src/main/java/tassist/address/logic/parser/EditCommandParser.java
- src/main/java/tassist/address/logic/parser/ParserUtil.java
- src/main/java/tassist/address/model/person/Person.java
- src/main/java/tassist/address/model/person/Progress.java
- src/main/java/tassist/address/model/util/SampleDataUtil.java
- src/main/java/tassist/address/storage/JsonAdaptedPerson.java
- src/main/java/tassist/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/tassist/address/logic/LogicManagerTest.java
- src/test/java/tassist/address/logic/commands/CommandTestUtil.java
- src/test/java/tassist/address/logic/commands/EditCommandTest.java
- src/test/java/tassist/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/tassist/address/logic/parser/AddCommandParserTest.java
- src/test/java/tassist/address/logic/parser/ParserUtilTest.java
- src/test/java/tassist/address/model/person/PersonTest.java
- src/test/java/tassist/address/storage/JsonAdaptedPersonTest.java
- src/test/java/tassist/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/tassist/address/testutil/PersonBuilder.java
- src/test/java/tassist/address/testutil/PersonUtil.java
- src/test/java/tassist/address/testutil/TypicalPersons.java
> Create Progress class

- src/main/java/tassist/address/ui/PersonCard.java
Closes #73 
Add missing @FXML in PersonCard.java
> Fix UI Bug

- src/main/java/tassist/address/MainApp.java
> TAssist release v1.3

- src/main/java/tassist/address/logic/commands/DeleteCommand.java
- src/main/java/tassist/address/logic/parser/DeleteCommandParser.java
- src/test/java/tassist/address/logic/commands/DeleteCommandTest.java
- src/test/java/tassist/address/logic/parser/AddressBookParserTest.java
- src/test/java/tassist/address/logic/parser/DeleteCommandParserTest.java
> Add studentId to DeleteCommand

- src/main/java/tassist/address/logic/commands/AddCommand.java
- src/main/java/tassist/address/logic/parser/AddCommandParser.java
- src/main/java/tassist/address/model/person/Github.java
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/tassist/address/model/person/GithubTest.java
- src/test/java/tassist/address/testutil/PersonBuilder.java
> Create GithubTest class

- src/main/java/tassist/address/logic/commands/ListCommand.java
- src/test/java/tassist/address/logic/commands/ListCommandTest.java
> Update list command message and sorting feature

- src/main/java/tassist/address/logic/commands/AddCommand.java
- src/main/java/tassist/address/model/person/Person.java
- src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/tassist/address/logic/commands/CommandTestUtil.java
- src/test/java/tassist/address/model/person/PersonTest.java
- src/test/java/tassist/address/testutil/TypicalPersons.java
> Remove support for duplicate Student ID 

- src/main/java/tassist/address/logic/commands/ClassCommand.java
- src/main/java/tassist/address/logic/parser/ClassCommandParser.java
- src/test/java/tassist/address/logic/commands/ClassCommandTest.java
- src/test/java/tassist/address/logic/commands/CommandTestUtil.java
- src/test/java/tassist/address/logic/parser/ClassCommandParserTest.java
> Add student id to class command

- src/main/java/tassist/address/logic/commands/FindCommand.java
- src/main/java/tassist/address/logic/parser/FindCommandParser.java
- src/test/java/tassist/address/logic/commands/FindCommandTest.java
- src/test/java/tassist/address/logic/parser/FindCommandParserTest.java
> Add student ID to FindCommand

- src/main/java/tassist/address/logic/browser/DesktopBrowserService.java
- src/main/java/tassist/address/logic/commands/HelpCommand.java
- src/main/java/tassist/address/ui/HelpWindow.java
- src/main/java/tassist/address/ui/MainWindow.java
- src/test/java/tassist/address/logic/browser/DesktopBrowserServiceTest.java
- src/test/java/tassist/address/logic/commands/HelpCommandTest.java
- src/test/java/tassist/address/logic/parser/AddressBookParserTest.java
> Update help command link

- build.gradle
- src/main/java/tassist/address/logic/commands/AddCommand.java
- src/main/java/tassist/address/logic/commands/DeleteCommand.java
- src/main/java/tassist/address/model/AddressBook.java
- src/main/java/tassist/address/model/ModelManager.java
- src/main/java/tassist/address/model/person/UniquePersonList.java
> Add assertions

- src/main/java/tassist/address/logic/commands/AssignCommand.java
> Fix assignment status to update automatically on UI

- src/main/java/tassist/address/logic/parser/AssignmentCommandParser.java
- src/test/java/tassist/address/logic/parser/AddCommandParserTest.java
- src/test/java/tassist/address/logic/parser/AssignmentCommandParserTest.java
> Add duplicate prefix check for assignment related commands

- docs/UserGuide.md
- src/main/java/tassist/address/logic/Logic.java
- src/main/java/tassist/address/logic/LogicManager.java
- src/main/java/tassist/address/model/AddressBookModel.java
- src/main/java/tassist/address/model/Model.java
- src/main/java/tassist/address/model/ModelManager.java
- src/main/java/tassist/address/ui/CalendarView.java
- src/main/java/tassist/address/ui/MainWindow.java
- src/main/java/tassist/address/ui/TimeEventCard.java
- src/main/java/tassist/address/ui/TimeEventListPanel.java
- src/main/resources/view/BaseTheme.css
- src/main/resources/view/BrightTheme.css
- src/main/resources/view/CalendarView.fxml
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/PinkTheme.css
- src/main/resources/view/TimeEventCard.fxml
- src/main/resources/view/TimeEventListPanel.fxml
- src/test/java/tassist/address/logic/commands/AddCommandTest.java
> Add support to view TimedEvents

- src/main/java/tassist/address/ui/CommandBox.java
- src/main/java/tassist/address/ui/MainWindow.java
- src/main/resources/view/MainWindow.fxml
The app uses GUI interactions to change theme and views.
Using hotkeys for these actions will enahnce usability. This allows tutors to stay free from their mouse and stick to using keyboards for maximum efficiency.
Let's:
- Implement F2 hotkey to cycle through the themes
- Implement F3 hotkey to cycle through views between calendar view and student card view
This way, it provides faster operations and improve tutor experience. Furthermore, these hotkeys are next to each other and combined with the F1 hotkey for help, concentrates hotkeys in the same part of the keyboard.
Closes #144 , closes #155
> Add hotkeys to theme and view

- src/main/java/tassist/address/logic/commands/AssignmentCommand.java
- src/test/java/tassist/address/logic/commands/CommandTestUtil.java
- src/test/java/tassist/address/logic/commands/ViewCommandTest.java
- src/test/java/tassist/address/logic/parser/AssignCommandParserTest.java
- src/test/java/tassist/address/logic/parser/AssignmentCommandParserTest.java
> Standardize assignment related testing

- docs/diagrams/UiClassDiagram.puml
> Update UI class diagram

- docs/diagrams/ListSequenceDiagram.puml
> Add list sequence diagram

- src/main/java/tassist/address/logic/commands/ListCommand.java
- src/test/java/tassist/address/logic/commands/ListCommandTest.java
- src/test/java/tassist/address/model/person/ProjectTeamTest.java
> Fix list filtering using ProjectTeam

- docs/UserGuide.md
> Update user guide (v1.4)

- src/main/java/tassist/address/logic/commands/ListCommand.java
> Edit List error message 

- src/main/java/tassist/address/logic/commands/ClassCommand.java
- src/test/java/tassist/address/logic/commands/ClassCommandTest.java
> Update class command to preserve assignments

- src/main/java/tassist/address/logic/parser/ClassCommandParser.java
- src/test/java/tassist/address/logic/parser/ClassCommandParserTest.java
> Prevent duplicate syntax from being accepted when using class command

- src/main/java/tassist/address/logic/commands/GithubCommand.java
- src/test/java/tassist/address/logic/commands/GithubCommandTest.java
> Update github command to preserve assignments

- src/main/java/tassist/address/logic/parser/GithubCommandParser.java
- src/test/java/tassist/address/logic/parser/GithubCommandParserTest.java
> Prevent duplicate syntax from being accepted when using github command

- docs/diagrams/DeleteSequenceDiagram.puml
> Update delete command sequence diagram

- src/main/java/tassist/address/model/timedevents/TimedEvent.java
- src/test/java/tassist/address/model/timedevents/AssignmentTest.java
> Handle Assignment duplicate name

- src/main/java/tassist/address/logic/commands/ClassCommand.java
- src/main/java/tassist/address/logic/commands/ClearCommand.java
- src/main/java/tassist/address/logic/commands/GithubCommand.java
- src/main/java/tassist/address/logic/commands/UnassignCommand.java
- src/main/java/tassist/address/logic/commands/ViewCommand.java
- src/test/java/tassist/address/logic/commands/ClassCommandTest.java
- src/test/java/tassist/address/logic/commands/ClearCommandTest.java
- src/test/java/tassist/address/logic/commands/GithubCommandTest.java
- src/test/java/tassist/address/logic/commands/UnassignCommandTest.java
- src/test/java/tassist/address/logic/commands/ViewCommandTest.java
> Add tostring methods for all commands

- src/main/java/tassist/address/logic/Messages.java
> Fix person not found message

- src/main/java/tassist/address/model/person/Person.java
- src/test/java/tassist/address/model/person/PersonTest.java
> Standardize person equals

- src/main/java/tassist/address/commons/util/StringUtil.java
- src/main/java/tassist/address/logic/commands/FindCommand.java
- src/main/java/tassist/address/logic/parser/FindCommandParser.java
- src/test/java/tassist/address/commons/util/StringUtilTest.java
- src/test/java/tassist/address/logic/commands/FindCommandTest.java
- src/test/java/tassist/address/logic/parser/FindCommandParserTest.java
- src/test/java/tassist/address/model/person/NameContainsKeywordsPredicateTest.java
Updates FindCommand to find partial matches and class number
Closes #190 , closes #191
> Update find command

- src/main/java/tassist/address/logic/commands/AssignCommand.java
- src/test/java/tassist/address/logic/commands/AssignmentCommandTest.java
> Disallow assigning overdue timed events

- src/test/java/tassist/address/model/person/ProgressTest.java
> Add Progress tests

- src/main/java/tassist/address/logic/LogicManager.java
- src/main/java/tassist/address/logic/commands/OpenCommand.java
- src/test/java/tassist/address/logic/LogicManagerTest.java
- src/test/java/tassist/address/logic/browser/DesktopBrowserServiceTest.java
- src/test/java/tassist/address/logic/commands/OpenCommandTest.java
> Update browserService implementation

- docs/UserGuide.md
> Update FindCommand in UG

- docs/UserGuide.md
> Update DeleteCommand in UG

- src/main/java/tassist/address/logic/commands/ClassCommand.java
- src/main/java/tassist/address/logic/parser/ClassCommandParser.java
- src/main/java/tassist/address/model/person/ClassNumber.java
- src/test/java/tassist/address/logic/parser/ClassCommandParserTest.java
> Disallow "No tutorial assigned" to remove class

- src/main/java/tassist/address/logic/commands/ListCommand.java
- src/main/java/tassist/address/logic/parser/ListCommandParser.java
- src/main/java/tassist/address/model/person/Person.java
- src/test/java/tassist/address/logic/commands/ListCommandTest.java
- src/test/java/tassist/address/logic/parser/AddressBookParserTest.java
- src/test/java/tassist/address/logic/parser/ListCommandParserTest.java
- src/test/java/tassist/address/testutil/TypicalPersons.java
> Update list command 'course' --> 'class'

- src/main/java/tassist/address/logic/commands/GithubCommand.java
- src/main/java/tassist/address/logic/parser/GithubCommandParser.java
- src/main/java/tassist/address/model/person/Github.java
- src/test/java/tassist/address/logic/commands/GithubCommandTest.java
- src/test/java/tassist/address/logic/parser/GithubCommandParserTest.java
Closes #198 
Closes #184
Closes #206
> Allow github to have multiple "no assigned github"

- docs/UserGuide.md
> Update UG - import and export commands

- src/main/java/tassist/address/logic/commands/AddCommand.java
- src/main/java/tassist/address/logic/commands/AssignmentCommand.java
- src/main/java/tassist/address/logic/commands/ClassCommand.java
- src/main/java/tassist/address/logic/commands/DeleteCommand.java
- src/main/java/tassist/address/logic/commands/EditCommand.java
- src/main/java/tassist/address/logic/commands/ExportCommand.java
- src/main/java/tassist/address/logic/commands/FindCommand.java
- src/main/java/tassist/address/logic/commands/GithubCommand.java
- src/main/java/tassist/address/logic/commands/HelpCommand.java
- src/main/java/tassist/address/logic/commands/ImportCommand.java
- src/main/java/tassist/address/logic/commands/ListCommand.java
- src/main/java/tassist/address/logic/commands/OpenCommand.java
- src/main/java/tassist/address/logic/commands/ProgressCommand.java
- src/main/java/tassist/address/logic/commands/RepoCommand.java
- src/main/java/tassist/address/logic/commands/UnassignCommand.java
- src/main/java/tassist/address/logic/parser/ListCommandParser.java
- src/main/java/tassist/address/logic/parser/RepoCommandParser.java
- src/main/java/tassist/address/model/person/Github.java
- src/main/java/tassist/address/model/person/Name.java
- src/main/java/tassist/address/model/person/Repository.java
- src/main/java/tassist/address/model/person/StudentId.java
- src/test/java/tassist/address/logic/commands/RepoCommandTest.java
- src/test/java/tassist/address/logic/parser/RepoCommandParserTest.java
> Improve code quality

- src/main/java/tassist/address/logic/commands/EditCommand.java
- src/main/java/tassist/address/model/person/Email.java
- src/main/java/tassist/address/model/person/Phone.java
> Edit phone number limit

- docs/UserGuide.md
- src/main/java/tassist/address/model/person/Repository.java
Closes #340 
Closes #327 
Closes #296
> Update User Guide

- src/main/java/tassist/address/logic/commands/AddCommand.java
- src/main/java/tassist/address/logic/commands/EditCommand.java
- src/test/java/tassist/address/logic/commands/AddCommandTest.java
- src/test/java/tassist/address/logic/commands/EditCommandTest.java
Closes #337 
Default github is no longer checked as a duplicate
> Fix duplication check logic of Github

- docs/diagrams/ClassSequenceDiagram.puml
- docs/diagrams/ModelClassDiagram.puml
> Add class command sequence diagram

- src/main/java/tassist/address/logic/parser/ListCommandParser.java
- src/test/java/tassist/address/logic/parser/ListCommandParserTest.java
> Tighten list command input validation

- docs/UserGuide.md
> Update list command user guide

- src/main/java/tassist/address/logic/commands/AddCommand.java
> Add square bracket

- docs/DeveloperGuide.md
- src/main/java/tassist/address/logic/commands/ListCommand.java
> Update DG - Add use cases for the list command

- docs/UserGuide.md
- src/main/java/tassist/address/logic/parser/FindCommandParser.java
- src/main/java/tassist/address/model/person/Name.java
- src/test/java/tassist/address/logic/parser/FindCommandParserTest.java
- src/test/java/tassist/address/model/person/NameTest.java
> Branch make name strictly numerical

- src/main/java/tassist/address/logic/parser/ImportCommandParser.java
- src/main/java/tassist/address/logic/parser/ParserUtil.java
- src/test/java/tassist/address/logic/parser/ParserUtilTest.java
> Add invalid path check for windows in import and export

- src/main/java/tassist/address/logic/commands/ListCommand.java
> Fix list command error message

- src/main/java/tassist/address/ui/CalendarView.java
- src/main/resources/view/CalendarView.fxml
Now always show a vertical scrollbar, closes #300 
Now shows index, closes #304
> Update calendar view

- docs/UserGuide.md
- src/main/java/tassist/address/logic/commands/AssignCommand.java
- src/main/java/tassist/address/logic/parser/AssignCommandParser.java
- src/test/java/tassist/address/logic/parser/AssignCommandParserTest.java
> Standardize parameter order of assigncommand
